name: Deploy client

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy via surge
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: npm install -g surge
      - run: yarn
        working-directory: ./client
      - run: yarn build
        working-directory: ./client
      - run: surge ./client/build red-king.pdavids.website --token ${{ secrets.SURGE_TOKEN }}
