name: Deploy client

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy via surge
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: npm install -g surge
      - run: yarn
      - run: yarn build
      - run: cp index.html 200.html
        working-directory: ./packages/client/build
      - run: surge ./packages/client/build red-queen.pdavids.website --token ${{ secrets.SURGE_TOKEN }}
